### ISSUE TITLE
KeyError on attempted login

### ISSUE THREAD

**Issue by LorenDB** [n4n0GH/ulauncher_clockify#8]
I followed the instructions to set up the Clockify extension, but when I clicked Save, I got this error:

---
Message: 'com.github.n4n0gh.ulauncher_clockify'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.n4n0gh.ulauncher_clockify'

```

**Comment by LorenDB** [comment]
Please disregard; I needed to install the python-dateutil and pytz modules.
